FROM node:16-alpine as build
RUN npm install -g npm@6.14.7
RUN mkdir -p /var/www/app
WORKDIR /var/www/app
COPY ./package.json ./package-lock.json ./
RUN npm ci
COPY . var/www/app
ENV NODE_ENV=develpoment
RUN npm run build
EXPOSE 1337
CMD ["npm", "run", "develop"]
