#FROM node:16-alpine as build
#RUN npm install -g npm@6.14.7
#RUN mkdir -p /var/www/strapit-roinvesting
#WORKDIR /var/www/strapit-roinvesting
#ADD . /var/www/strapit-roinvesting
#RUN npm ci
#CMD npm run start
#ENV NODE_ENV=develpoment
#EXPOSE 1337
